### ISSUE TITLE
More details (or pictures for set up step by step?) about "Sunrise Robot Application upload" ?

### ISSUE THREAD

**Issue by CodingCatMountain** [epfl-lasa/iiwa_ros#103]
Hi, I am very grateful for the development that you have been done, cause this repo and iiwa_stack do really help the guys who are not familiar to Java..  However, when we try to setup this repo into sunrise os, we encounter a problems which is **we couldn't find the [FRI] tab**... We believe we have followed the instructions in "Sunrise Robot Application upload" except for the [FRI] tab.. Could you share more details or even pictures in "Sunrise Robot Application upload"? Thank you. Looking forward to your reply!!

**Comment by CodingCatMountain** [comment]
It is so weird.. We can't see the **[FRI]** tab while we can connect the iiwa via KONI. It works, but it is so weird, just like a magic.. And it can't connect again after I run the **PositionAndGMSReferencing** (an official demo, may can be used to calibration) for calibrating. I choose to restart the robot, then it worked again.

**Comment by costashatz** [comment]
@CodingCatMountain have you found a solution to your problems?

**Comment by CodingCatMountain** [comment]
> @CodingCatMountain have you found a solution to your problems?

Hi, costashatz.  Thank you for your reply. Unfortunately, I don't have found the solution. So far, I just try to restart the robot to avoiding this problem. May be this is not a big deal. I will close this issue.
