### ISSUE TITLE
Unexpected Connection Break Without Warning and Emergency Stop

### ISSUE THREAD

**Issue by anubhav-dogra** [epfl-lasa/iiwa_ros#116]
Hi @costashatz 
Have you ever found this issue ? 

I am using this library from quite a while now, and  while running experiments, I do find that robot just stops working after a sometime (may be an hour or so). There is no error on the smartpad or on the ROS machine. I have noticed that the Application status just turns off ! 
Here is the screenshot of the SmartPad.
![image](https://github.com/epfl-lasa/iiwa_ros/assets/44242975/444e9246-a6b7-43b8-87c9-a49267325031)

After this, robot stays at whatever controller it was booted on. For example it stays in Torque mode (stiffness Zero) or PositionController with stiffness X.  Next step for me it just to press the emergency stop!

Later on, If I close FRI application and rerun it again, I got his error:
![image](https://github.com/epfl-lasa/iiwa_ros/assets/44242975/7c4bdebf-b8db-4d7b-877f-05b3b3953705)

I can only make it work if I restart robot controller. 

Any comments please ?

**Comment by matthias-mayr** [comment]
I missed that issue apparently
> I am using this library from quite a while now, and while running experiments, I do find that robot just stops working after a sometime (may be an hour or so). There is no error on the smartpad or on the ROS machine. I have noticed that the Application status just turns off !

I have no memories of this pattern. I had disconnects into the past until I pushed some changes to the driver. Then it was working fine for me with a preempt_rt kernel. iirc, I used 500 Hz most of the time.

What is important to fully reset the program though is to untick the current program in the list of applications and then select it again. This is a bit finicky since the checkbox is not that easy to hit on the smartpad. But this is the procedure I always went through.

**Comment by anubhav-dogra** [comment]
Hi @matthias-mayr 
Thanks for your response. What I am noticing is I think beyond this library. Because in my case, Kuka becomes unresponsive (even from the smartpad) after like 45 mins or so. 
I have contacted KUKA support, and waiting for their response.

**Comment by anubhav-dogra** [comment]
@matthias-mayr 
Finally found it! I actually was ignoring this since long, coz we barely used our robot for more then an hour to complete one single task.

This is actually very specific to the medical grade robot. It requires to perform the Brake Test after every reboot. So, if breaktest is not performed, robot will stop working after an hour or so. 

:)
