### ISSUE TITLE
Link with moveit to control real kuka iiwa robot 

### ISSUE THREAD

**Issue by chunxuli90** [epfl-lasa/iiwa_ros#12]
Hi,

Currently I am already able to send text data based command via rqt-gui to control the real robot using FRI. But I want to do it with visual monitoring. Can this repo mix with moveit to control the real robot by using the motion planning function? I only have the FRI without Serving motors packages in the KUKA side.

Thank you.

**Comment by costashatz** [comment]
> Can this repo mix with moveit to control the real robot by using the motion planning function? I

Not yet! But #10 will do exactly this.. I need to find time to review this PR and then I will merge..

**Comment by costashatz** [comment]
By the way, you can use rviz to visualize the current state of the robot etc..
