### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by 921218316** [epfl-lasa/iiwa_ros#17]
I configure the IP as the steps   [https://github.com/epfl-lasa/iiwa_ros/issues/14](url)，and I can ping the robot, but when I run the app FRIOverlay in SmartPad and with 10s I have run the roslaunch iiwa_driver iiwa_bringup.launch. I get a timeout error, I can't see the [FRI] tab.
![1571491369(1)](https://user-images.githubusercontent.com/49083996/67145801-15314c00-f2b7-11e9-81f5-4dd5d8902176.jpg)
![fe719be66c27677d9c207981d1179a8](https://user-images.githubusercontent.com/49083996/67145938-95a47c80-f2b8-11e9-8d74-d6f36dfbbda8.jpg)

**Comment by costashatz** [comment]
Are you sure your dependencies are installed? Can you try launching the gazebo file? `roslaunch iiwa_gazebo iiwa_gazebo.launch` and let us know what you get..

**Comment by 921218316** [comment]
When I launch the gazebo, it shows that..,
![image](https://user-images.githubusercontent.com/49083996/67146952-f20c9980-f2c2-11e9-8456-552d3d503ed7.png)

**Comment by costashatz** [comment]
Can I have the terminal output also? Thanks!

**Comment by 921218316** [comment]
here are terminal outputs
![image](https://user-images.githubusercontent.com/49083996/67147099-45cbb280-f2c4-11e9-9091-99f7f5e424a0.png)
![image](https://user-images.githubusercontent.com/49083996/67147103-4ebc8400-f2c4-11e9-91f9-b6adb4fd171a.png)
![image](https://user-images.githubusercontent.com/49083996/67147106-567c2880-f2c4-11e9-9ba0-8199c1f92fc8.png)
![image](https://user-images.githubusercontent.com/49083996/67147111-5f6cfa00-f2c4-11e9-8a0b-4180e45c7a4f.png)

**Comment by costashatz** [comment]
Something un-related to your issue is that you haven't installed/linked properly to the RBDyn library.

Back to your problem, everything seems to be installed correctly. Are you sure that the IPs are correctly set? Please go back to the README and re-do all the steps..

**Comment by 921218316** [comment]
I re-do all the steps as  README again.The IPs I configure:  Windows laptop is connected on the X66 Ethernet port and has IP 172.31.1.42 mask 255.255.0.0,Linux/ROS laptop is connected on the KONI Ethernet port and has IP 192.170.10.1 mask 255.255.255.0, but It doesn't work anyway

**Comment by 921218316** [comment]
On the SmartPAD there is no [FRI] tab in the I/O Groups,is this where the problem lay? If so,how to fix it

**Comment by costashatz** [comment]
@921218316 I think I know what's happening. The computer of KUKA has two ethernet ports. One that you should connect in Windows to upload the apps etc., and one for the FRI communication. Are you using this one when connecting to iiwa_ros?

**Comment by 921218316** [comment]
I don't connect as you mentioned above. I do it as the following picture shows
![1571734982(1)](https://user-images.githubusercontent.com/49083996/67271799-dafdbf80-f4ed-11e9-8f17-d087c58dd3aa.jpg)

**Comment by costashatz** [comment]
You should connect your linux machine to the KONI or KOIN (no idea what is correct) ethernet port.. Also double check all your IPs..

**Comment by 921218316** [comment]
I'm sorry for the wrong picture.It is actually like this.
![1571738906(1)](https://user-images.githubusercontent.com/49083996/67276832-0e454c00-f4f8-11e9-8d4a-088773800f9c.jpg)

 I checked the IPs,it is correct as the picture shows.I can ping on the ros laptop to the sunrise cabinet.And I can also ping on the workbench laptop to the sunrise cabinet

**Comment by 921218316** [comment]
I first start the ros controller by the command line `roslaunch iiwa_driver iiwa_bringup.launch` and then start the appliaction in the SmartPAD,but it doesn't work.And there is no [FRI] tab the I/O groups .
![1424306465](https://user-images.githubusercontent.com/49083996/67830686-8b834900-fb16-11e9-9e49-8b1bd4e445e5.jpg)
![1389274732](https://user-images.githubusercontent.com/49083996/67830689-8cb47600-fb16-11e9-93ba-1ff2cb3d0ee4.jpg)
![93923878](https://user-images.githubusercontent.com/49083996/67830691-8e7e3980-fb16-11e9-8363-8b283c175e4d.jpg)

**Comment by costashatz** [comment]
> And there is no [FRI] tab the I/O groups .

There shouldn't be any.. We do not have and it works..

Please make sure that everything is connected and with proper IPs..

**Comment by 921218316** [comment]
Thank you! I re-assign the port to RTOS:
`C:\KUKA\Hardware\Manager\KUKAHardwareManager.exe -assign OptionNIC -os RTOS`
And it works now!
Thank you very much again!

**Comment by costashatz** [comment]
Great news! Closing the issue! Feel free to re-open a new issue if something arises!

**Comment by emielke12** [comment]
I'm experiencing the same issue here, the Timeout is occuring sporadically. Sometimes I can connect, and others not, without changing anything between launches. Any ideas?

**Comment by matthias-mayr** [comment]
I had this issue as well and it got a lot better when using it with #47 and #48, especially when using the latter one.

**Comment by emielke12** [comment]
@matthias-mayr I'll try them out. Thanks for pointing me to those!

**Comment by mf093087** [comment]
> Thank you! I re-assign the port to RTOS:
> `C:\KUKA\Hardware\Manager\KUKAHardwareManager.exe -assign OptionNIC -os RTOS`
> And it works now!
> Thank you very much again!

May I ask, what do you mean by 're-assign the port to RTOS:
> `C:\KUKA\Hardware\Manager\KUKAHardwareManager.exe -assign OptionNIC -os RTOS` . Is it in ubuntu or in windows?

**Comment by mf093087** [comment]
> I had this issue as well and it got a lot better when using it with #47 and #48, especially when using the latter one.

Hi, Matthias, I tried your solution but it still doesn't work, I still receive the error timeout before FRI connection....

**Comment by emielke12** [comment]
@mf093087 That's a .exe, so it is Windows. I believe this is done on the cabinet PC.

**Comment by mf093087** [comment]
May I ask, after re-assign the port to RTOS:
C:\KUKA\Hardware\Manager\KUKAHardwareManager.exe -assign OptionNIC -os RTOS

Should we turn off the kuka controller and remove the external monitor, and then use the AUT mode on smartpad? Can we use AUT mode on the external monitor with windows?

**Comment by CodingCatMountain** [comment]
> @mf093087 That's a .exe, so it is Windows. I believe this is done on the cabinet PC.

Hi, @emielke12 . Have you solved this connection problem?? Actually this comments: 

` C:\KUKA\Hardware\Manager\KUKAHardwareManager.exe -assign OptionNIC -os RTOS`, it should be run on the windows 7 which installed on the computers. However, in our group, we also try this command which have to get into the windows 7 in the controller.. the [FRI] tab still is missing..
