### ISSUE TITLE
about position control mode and joint impedance control

### ISSUE THREAD

**Issue by jacknlliu** [epfl-lasa/iiwa_ros#21]
Whether the joint position control mode via ros control is the joint impedance control mode of iiwa controller.

**Comment by costashatz** [comment]
Indeed it is (see [here](https://github.com/epfl-lasa/iiwa_ros/blob/master/iiwa_driver/java/FRIOverlay.java#L122)), if I understand KUKA's documentation correctly.

**Comment by costashatz** [comment]
@jacknlliu closing this issue.. In any case you have any other questions, let me know..
