### ISSUE TITLE
difference between the origin FRI and the modified FRI library

### ISSUE THREAD

**Issue by jacknlliu** [epfl-lasa/iiwa_ros#22]
What's the difference between the origin FRI and the modified FRI library?

**Comment by costashatz** [comment]
> What's the difference between the origin FRI and the modified FRI library?

Very minor differences.. Mainly formatting and making a few functions available to the public API. I intent to write an FRI library that does not use any code of KUKA and thus I could make it completely free. But I do not have the time at the moment..

**Comment by jacknlliu** [comment]
Thanks for making it clear!
