### ISSUE TITLE
How to get FRI library?

### ISSUE THREAD

**Issue by leledeyuan00** [epfl-lasa/iiwa_ros#23]
I'm trying to use FRI to connect our iiwa robots. But I can't connect my robot successfully.
It always in the monitoring state, like robot never get any message from my PC.
I would like to reference your code.
Would you mind sharing your private library code for me? 
Thank you!

**Comment by costashatz** [comment]
> I'm trying to use FRI to connect our iiwa robots. But I can't connect my robot successfully.

Do you have FRI installed on KUKA Sunrise and upload it to the robot? This has nothing to do with this package. This is the FRI capability provided by KUKA. If you do not have this, then you cannot use iiwa_ros to connect to the FRI interface of the robot.

> Would you mind sharing your private library code for me?

Please send me an e-mail (konstantinos.chatzilygeroudis@epfl.ch) along with a verification that you own a KUKA manipulator (e.g. picture with a serial number and the robot). This code is just for connecting to a robot already with FRI capability.
