### ISSUE TITLE
default torque controller with gazebo

### ISSUE THREAD

**Issue by jacknlliu** [epfl-lasa/iiwa_ros#24]
Is the default torque controller with gazebo an open-loop controller?

**Comment by costashatz** [comment]
It is not a controller actually. It just takes torques and sends them to the robot.. The gravity compensation should be on though by default..

**Comment by jacknlliu** [comment]
@costashatz  what's the frequency of the gravity compensation? Is it the same as the frequency of the gazebo physics engine?

**Comment by costashatz** [comment]
Yes.. it's running inside the simulation loop..
