### ISSUE TITLE
How to verify the torque controller is correct

### ISSUE THREAD

**Issue by 921218316** [epfl-lasa/iiwa_ros#29]
There are two controller: PositionController and TorqueController. The PositionController is simple to understand, but how to verify the torque controller is correct? Is there any method in gazebo simulation environment?

**Comment by costashatz** [comment]
> how to verify the torque controller is correct?

What do you mean verify that is correct? The torque controller will just forward the torques to the robot (either simulated or real robot).

**Comment by 921218316** [comment]
The command /iiwa/TroqueController/command send to the robot in the gazebo, so I want to know the effect of the robot movement，like joint position, joint velocity, joint acceleration,  after the torque command is applied to verify it is crroct

**Comment by costashatz** [comment]
> so I want to know the effect of the robot movement，like joint position, joint velocity, joint acceleration, after the torque command is applied

You can use the topic `/iiwa/joint_states` to track the movement of the arm (it gives joint positions, velocities and torques. But this has nothing to do with the package (if it is "correct" or not; I am not even sure what you mean). Gazebo takes the current state, the commanded torque and uses a physics library to simulate the real-world (by default Gazebo use ODE).

I am closing this issue. Feel free to re-open it if you have any further issues/questions.
