### ISSUE TITLE
Compilation with iiwa_service

### ISSUE THREAD

**Issue by Lejou** [epfl-lasa/iiwa_ros#55]
I have already install all the dependencies that the project needs, and when I "catkin_make" my ROS workspace, I have the error with iiwa_service, like this:

![image](https://user-images.githubusercontent.com/33564160/112616164-593a6000-8e5e-11eb-9f39-b4a40895b38a.png)

How can I figure out this problem? What happened to this? Could anyone give me a hand?

**Comment by matthias-mayr** [comment]
It's a linker error since it can not link to one of the dependencies, `rbd`. The first thing that you can check  that you correctly compiled and installed the dependencies.

**Comment by costashatz** [comment]
Did you install the non-ROS dependencies? See [here](https://github.com/epfl-lasa/iiwa_ros#dependencies) for instructions..

**Comment by Lejou** [comment]
I am pleased to tell you that what u guys told me is right. Some dependencies are not installed in the right way. I install them again, and the compilation is complete. Appreciate! Thank you very much!!!!
