### ISSUE TITLE
safety error in safety configuration of sunrise workbench and in smartpad

### ISSUE THREAD

**Issue by mf093087** [epfl-lasa/iiwa_ros#63]
I am following the tutorials to use the KUKA iiwa package. 
1. In the 'Sunrise Robot Application upload' section, I need to set the safety configurations. In my sunrise, I can only set 3 axises not 7 axises.
![image](https://user-images.githubusercontent.com/67538561/130366922-9ce59c1b-4b75-4482-9e5e-2d0091a993df.png)

2. When I modify my sunrise file without the safety configuration, I synchronize the project to smartPAD. In my smart pad, the light for the safety is always red. 
I met the error 
_Safety control
position sensor not referenced(K1:A1,A2,A3,A4,A5,A6,A7).
Emergency stop external is active.
protective stop is activated_
![3505bf3bcd8ba3e9aec788fc5165c47](https://user-images.githubusercontent.com/67538561/130367138-b3702923-f263-4c4a-9166-16a0f767673a.jpg)

**Comment by mf093087** [comment]
problem solved with deactivate the emergency stop external and protective stop in KUKA sunrise workbench

**Comment by costashatz** [comment]
@mf093087 good to know! Closing the issue.
