### ISSUE TITLE
safety error: operation safety is active

### ISSUE THREAD

**Issue by mf093087** [epfl-lasa/iiwa_ros#64]
I switched the smart pad to AUT mode, then I met another safety error:\

operation safety is active. 
![3505bf3bcd8ba3e9aec788fc5165c47](https://user-images.githubusercontent.com/67538561/130368540-fae9369d-19fb-4350-9e66-ecab94c1fbb6.jpg)

Then what does press mechanical button mean ?
![image](https://user-images.githubusercontent.com/67538561/130368569-3487e557-ae97-416e-88fd-3d81f3165b2e.png)
![44efe103e68bfd70ee3c6ec12609cec](https://user-images.githubusercontent.com/67538561/130368582-b993ab8d-6728-4d0c-83fb-47865b7ea15b.jpg)

**Comment by costashatz** [comment]
Did the solution of #63 fix the issue here as well?

**Comment by mf093087** [comment]
Yes
