### ISSUE TITLE
Connection issues, timeout before FRI connection quality reached good or excellent.

### ISSUE THREAD

**Issue by mf093087** [epfl-lasa/iiwa_ros#65]
I set up the robot and met this problem on the smart pad. 

_timeout before FRI connection quality reached good or excellent._
![c6c5e2a2aea83654ad6b72e6210cb7a](https://user-images.githubusercontent.com/67538561/130673958-42e054ab-09e6-4770-b2e2-7740b996c940.jpg)
And this is the screenshot from the UBUNTU.
![01](https://user-images.githubusercontent.com/67538561/130674742-1df9d197-4b95-4e82-90e0-cef968f4264b.png)
![02](https://user-images.githubusercontent.com/67538561/130674756-0145f1b3-8f09-4002-968c-969a2a557faa.png)
![03](https://user-images.githubusercontent.com/67538561/130674781-63076b1a-6007-4cc2-890f-c86772d7268d.png)

I tried the solution, which is provided by  921218316. 
https://github.com/epfl-lasa/iiwa_ros/issues/17

But it still doesn't work, then I tried this solution, it still didn't work. 
https://github.com/epfl-lasa/iiwa_ros/pull/48

Could you please help me? I assume it is because I am using ubuntu virtual machine on the same computer of the windows laptop. Should I use two separate computers?

**Comment by mf093087** [comment]
When I switch to dual system, it works. I am not sure why it doesn't work in virtual machine, can anybody help me?

**Comment by costashatz** [comment]
> I am not sure why it doesn't work in virtual machine, can anybody help me?

My best guess is that Virtual Machine does not have enough CPU power to keep the connection loop at 1KHz/500Hz.

**Comment by mf093087** [comment]
I tried dual system, it worked. But I think you should give an instruction about how to use the library on virtual machine. That would be very helpful.

**Comment by costashatz** [comment]
> I tried dual system, it worked. But I think you should give an instruction about how to use the library on virtual machine. That would be very helpful.

As I said in the comment above: `I do not think that the Virtual Machine have enough CPU power to keep the connection loop at 1KHz/500Hz.` Maybe if you give it more vCPUs, but still you would need priority to serial ports etc. Not worth the work.

Closing this issue..

**Comment by mf093087** [comment]
I don't think it has something to do with the CPU power, in my case, I already gave enough CPU power. I think something is not correct with the IP settings. I already assigned a static IP address to the virtual machine. But because I am not so familiar with the virtual machine IP setting, so I can't still connect to the robot with virtual machine. If an instruction about how to set the IP address and ping the robot in virtual machine would be very nice. However, if it is not worth the work, I might try to find solutions from somewhere else. 

Many thanks for your help, I think your library is very nice, this help me a lot.

**Comment by costashatz** [comment]
> I don't think it has something to do with the CPU power, in my case, I already gave enough CPU power. I think something is not correct with the IP settings. I already assigned a static IP address to the virtual machine. But because I am not so familiar with the virtual machine IP setting, so I can't still connect to the robot with virtual machine. If an instruction about how to set the IP address and ping the robot in virtual machine would be very nice. However, if it is not worth the work, I might try to find solutions from somewhere else.

I am pretty sure that even if you fix the IP issues (not sure IP setting is different than other PCs; I have barely used VMs --- my guess would be that you are not using the ethernet ports correctly), this will not be able to keep up the 500Hz/1KHz. We had big machine running native linux that if we didn't set high performance profile and we didn't give priority to hardware devices, they were not able to keep up the communication. So I really doubt that using a VM to run the iiwa_ros controller is a good option.

**Comment by mf093087** [comment]
> > I don't think it has something to do with the CPU power, in my case, I already gave enough CPU power. I think something is not correct with the IP settings. I already assigned a static IP address to the virtual machine. But because I am not so familiar with the virtual machine IP setting, so I can't still connect to the robot with virtual machine. If an instruction about how to set the IP address and ping the robot in virtual machine would be very nice. However, if it is not worth the work, I might try to find solutions from somewhere else.
> 
> I am pretty sure that even if you fix the IP issues (not sure IP setting is different than other PCs; I have barely used VMs --- my guess would be that you are not using the ethernet ports correctly), this will not be able to keep up the 500Hz/1KHz. We had big machine running native linux that if we didn't set high-performance profile and we didn't give priority to hardware devices, they were not able to keep up the communication. So I really doubt that using a VM to run the iiwa_ros controller is a good option.

Hi Costas, I think this makes sense, now I think I will keep on using a dual system, not VM. Because before I was trying to implement my approach on a dual system to VM. Now it seems to be not a good option...
