### ISSUE TITLE
Question about Sunrise Robot Application upload

### ISSUE THREAD

**Issue by zxl5344** [epfl-lasa/iiwa_ros#66]
I am a beginner of using iiwa robot. 

In repo, It mentioned: "Create a new Sunrise project with Sunrise Workbench". Where do I create this Sunrise project? On "a Windows laptop is connected on the X66 Ethernet port" or I can directly create on KUKA Sunrise Cabinet?  

If I have to use a laptop, how do I get Sunrise Workbench? 

Many thanks

**Comment by costashatz** [comment]
> "a Windows laptop is connected on the X66 Ethernet port"

If I understand well your question. This is where you should create the Sunrise Project.

> If I have to use a laptop, how do I get Sunrise Workbench?

KUKA should have given you this.

**Comment by zxl5344** [comment]
Thank you very much!
