### ISSUE TITLE
[ERROR] [1630537192.026313657, 222.275000000]: Could not load controller '/iiwa/TorqueController' because controller type 'effort_controllers/JointGroupEffortController' does not exist. [ERROR] [1630537192.026386756, 222.275000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types

### ISSUE THREAD

**Issue by mf093087** [epfl-lasa/iiwa_ros#67]
When I run gazebo, I receive following error
![image](https://user-images.githubusercontent.com/67538561/131756829-dffc2950-7664-4ed4-aeba-ab3fdc92ebfd.png)
![image](https://user-images.githubusercontent.com/67538561/131756843-569b9232-3a17-4f13-aa79-d11c22b11b9c.png)

**Comment by costashatz** [comment]
Which commands are you running?

**Comment by mf093087** [comment]
I am writing roslaunch iiwa_gazebo iiwa_gazebo.launch

**Comment by costashatz** [comment]
It seems that you have multiple instances running. "SpawnModel: Failure - model name iiwa already exist."

Also are you sure you have installed all the dependencies? Seems like it is failing to load the torque controller. Make sure that you have installed all ros-control.

**Comment by mf093087** [comment]
I am a little confused about how does the whole structure look like. Does it look like this? Should I rewrite the cmake list?

![image](https://user-images.githubusercontent.com/67538561/131926443-58117612-14a8-4fff-aaa5-f5723cfd9d41.png)

**Comment by costashatz** [comment]
You should not re-write CMakeLists. For ROS related things, we refer to the documentation of ROS: http://wiki.ros.org/Documentation

**Comment by mf093087** [comment]
Yes, I read that, but due to lack of experience, it is still hard for me to run this. Is it possible for you to show me how this installation work more clearly?
