### ISSUE TITLE
what is here source/directory

### ISSUE THREAD

**Issue by mf093087** [epfl-lasa/iiwa_ros#68]
I am new to ROS, I have trouble installing all the packages. I am sure there must be something wrong because I can't communicate with the robot. May I ask, what does source/directory mean?
![image](https://user-images.githubusercontent.com/67538561/131926897-676c848c-fe22-4ea1-9237-df71f606a59c.png)

Should the structure look like this?
![image](https://user-images.githubusercontent.com/67538561/131926982-cf8fd0f8-3fd8-4cb6-bca8-b9b8bfb82c29.png)
![image](https://user-images.githubusercontent.com/67538561/131927033-9f1d7026-c93f-4652-9306-7e763cf26d11.png)

**Comment by costashatz** [comment]
> Should the structure look like this?

Not exactly.. Although ROS would find what it needs to. In short, you should put all the non-ROS related dependencies outside the ROS workspace, and keep is ros_workspace/src only the ROS packages.

Overall, I suggest that you have a look at the ROS documentation: http://wiki.ros.org/Documentation. There are a lot of information there and tutorials. It will help you understand the basics.

Closing this as it is not related to iiwa_ros.
