### ISSUE TITLE
[iiwa/iiwa_service-2] process has died

### ISSUE THREAD

**Issue by mf093087** [epfl-lasa/iiwa_ros#69]
I successfully connect with the robot via FRI. 

When I run 'roslaunch iiwa_driver iiwa_bringup.launch', I met this error
 

But when I run 'roslaunch iiwa_driver iiwa_bringup.launch'. I met this error. 
![22](https://user-images.githubusercontent.com/67538561/132124126-8629230f-6364-4101-81e0-cf1085e9332b.png)

And when I run  'roslaunch iiwa_gazebo iiwa_gazebo.launch', I met this error.
![33](https://user-images.githubusercontent.com/67538561/132124135-2cf39a32-215e-483e-88e3-1aee41e91eb5.png)

Maybe I haven't installed the dependencies correctly. Could you please help me?

**Comment by costashatz** [comment]
> 'roslaunch iiwa_driver iiwa_bringup.launch'

This is intended to work only with the physical robot. You must ensure that the FRI app is running on the real KUKA and a connection is feasible.

> And when I run 'roslaunch iiwa_gazebo iiwa_gazebo.launch'

`roslaunch iiwa_gazebo iiwa_gazebo.launch` should be ran without `iiwa_bringup.launch`.

**Comment by zxl5344** [comment]
I have the same issues when I run command  'roslaunch iiwa_gazebo iiwa_gazebo.launch'. Other function like moveit is working. But there is no iiwa_service. Is anyone know how to solve it?

Here is my log:
... logging to /home/zxl5344/.ros/log/12d921ec-546e-11ec-bb30-45a21bc009e3/roslaunch-E5-ME-L-KAFI11-6075.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://E5-ME-L-KAFI11:35327/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /iiwa/CustomControllers/controllers/LinearDS/params: [1.0, 1.0, 1.0]
 * /iiwa/CustomControllers/controllers/LinearDS/type: LinearDSController
 * /iiwa/CustomControllers/controllers/PD/input: Orientation
 * /iiwa/CustomControllers/controllers/PD/output: Torque
 * /iiwa/CustomControllers/controllers/PD/params: [20.0, 2.0]
 * /iiwa/CustomControllers/controllers/PD/type: PidController
 * /iiwa/CustomControllers/controllers/PassiveDS/params: [200, 200]
 * /iiwa/CustomControllers/controllers/PassiveDS/type: PassiveDSController
 * /iiwa/CustomControllers/joints: ['iiwa_joint_1', ...
 * /iiwa/CustomControllers/params/end_effector: iiwa_link_ee
 * /iiwa/CustomControllers/params/null_space/Kd: 0.1
 * /iiwa/CustomControllers/params/null_space/Kp: 20.0
 * /iiwa/CustomControllers/params/null_space/joints: [0.04475269104532...
 * /iiwa/CustomControllers/params/null_space/max_torque: 10.0
 * /iiwa/CustomControllers/params/space: task
 * /iiwa/CustomControllers/structure/CascadeCtrl: ['LinearDS', 'Pas...
 * /iiwa/CustomControllers/type: iiwa_control/Cust...
 * /iiwa/PositionController/joints: ['iiwa_joint_1', ...
 * /iiwa/PositionController/type: position_controll...
 * /iiwa/PositionTorqueController/iiwa_joint_1/pid/d: 80.0
 * /iiwa/PositionTorqueController/iiwa_joint_1/pid/i: 100
 * /iiwa/PositionTorqueController/iiwa_joint_1/pid/i_clamp_max: 10000
 * /iiwa/PositionTorqueController/iiwa_joint_1/pid/i_clamp_min: -10000
 * /iiwa/PositionTorqueController/iiwa_joint_1/pid/p: 800.0
 * /iiwa/PositionTorqueController/iiwa_joint_2/pid/d: 100.0
 * /iiwa/PositionTorqueController/iiwa_joint_2/pid/i: 1000
 * /iiwa/PositionTorqueController/iiwa_joint_2/pid/i_clamp_max: 10000
 * /iiwa/PositionTorqueController/iiwa_joint_2/pid/i_clamp_min: -10000
 * /iiwa/PositionTorqueController/iiwa_joint_2/pid/p: 800.0
 * /iiwa/PositionTorqueController/iiwa_joint_3/pid/d: 80.0
 * /iiwa/PositionTorqueController/iiwa_joint_3/pid/i: 10
 * /iiwa/PositionTorqueController/iiwa_joint_3/pid/i_clamp_max: 10000
 * /iiwa/PositionTorqueController/iiwa_joint_3/pid/i_clamp_min: -10000
 * /iiwa/PositionTorqueController/iiwa_joint_3/pid/p: 800.0
 * /iiwa/PositionTorqueController/iiwa_joint_4/pid/d: 80.0
 * /iiwa/PositionTorqueController/iiwa_joint_4/pid/i: 10
 * /iiwa/PositionTorqueController/iiwa_joint_4/pid/i_clamp_max: 10000
 * /iiwa/PositionTorqueController/iiwa_joint_4/pid/i_clamp_min: -10000
 * /iiwa/PositionTorqueController/iiwa_joint_4/pid/p: 800.0
 * /iiwa/PositionTorqueController/iiwa_joint_5/pid/d: 10.0
 * /iiwa/PositionTorqueController/iiwa_joint_5/pid/i: 5
 * /iiwa/PositionTorqueController/iiwa_joint_5/pid/i_clamp_max: 10000
 * /iiwa/PositionTorqueController/iiwa_joint_5/pid/i_clamp_min: -10000
 * /iiwa/PositionTorqueController/iiwa_joint_5/pid/p: 300.0
 * /iiwa/PositionTorqueController/iiwa_joint_6/pid/d: 1.0
 * /iiwa/PositionTorqueController/iiwa_joint_6/pid/i: 1
 * /iiwa/PositionTorqueController/iiwa_joint_6/pid/i_clamp_max: 10000
 * /iiwa/PositionTorqueController/iiwa_joint_6/pid/i_clamp_min: -10000
 * /iiwa/PositionTorqueController/iiwa_joint_6/pid/p: 50.0
 * /iiwa/PositionTorqueController/iiwa_joint_7/pid/d: 1.0
 * /iiwa/PositionTorqueController/iiwa_joint_7/pid/i: 0.1
 * /iiwa/PositionTorqueController/iiwa_joint_7/pid/i_clamp_max: 10000
 * /iiwa/PositionTorqueController/iiwa_joint_7/pid/i_clamp_min: -10000
 * /iiwa/PositionTorqueController/iiwa_joint_7/pid/p: 10.0
 * /iiwa/PositionTorqueController/joints: ['iiwa_joint_1', ...
 * /iiwa/PositionTorqueController/type: effort_controller...
 * /iiwa/PositionTrajectoryController/action_monitor_rate: 30
 * /iiwa/PositionTrajectoryController/constraints/goal_time: 0.5
 * /iiwa/PositionTrajectoryController/joints: ['iiwa_joint_1', ...
 * /iiwa/PositionTrajectoryController/state_publish_rate: 25
 * /iiwa/PositionTrajectoryController/stop_trajectory_duration: 0
 * /iiwa/PositionTrajectoryController/type: position_controll...
 * /iiwa/TorqueController/joints: ['iiwa_joint_1', ...
 * /iiwa/TorqueController/type: effort_controller...
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_1/d: 100
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_1/i: 0.01
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_1/p: 700
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_2/d: 100
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_2/i: 100
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_2/p: 10000
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_3/d: 1
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_3/i: 35
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_3/p: 4500
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_4/d: 2
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_4/i: 60
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_4/p: 5500
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_5/d: 0.01
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_5/i: 30
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_5/p: 1000
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_6/d: 0.01
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_6/i: 0.1
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_6/p: 500
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_7/d: 0.01
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_7/i: 0.1
 * /iiwa/gazebo_ros_control/pid_gains/iiwa_joint_7/p: 100
 * /iiwa/joint_state_controller/publish_rate: 500
 * /iiwa/joint_state_controller/type: joint_state_contr...
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.15.13
 * /service/end_effector: iiwa_link_ee
 * /service/fk_service_name: iiwa_fk_server
 * /service/gravity_service_name: iiwa_gravity_server
 * /service/ik_service_name: iiwa_ik_server
 * /service/jacobian_deriv_service_name: iiwa_jacobian_der...
 * /service/jacobian_service_name: iiwa_jacobian_server
 * /service/jacobians_service_name: iiwa_jacobians_se...
 * /service/robot_description: /robot_description
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    urdf_spawner (gazebo_ros/spawn_model)
  /iiwa/
    iiwa_controller (controller_manager/spawner)
    iiwa_service (iiwa_tools/iiwa_service)

auto-starting new master
process[master]: started with pid [6141]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 12d921ec-546e-11ec-bb30-45a21bc009e3
process[rosout-1]: started with pid [6176]
started core service [/rosout]
process[iiwa/iiwa_service-2]: started with pid [6183]
/home/zxl5344/IROS2022/devel/lib/iiwa_tools/iiwa_service: error while loading shared libraries: libRBDyn.so.1: cannot open shared object file: No such file or directory
process[gazebo-3]: started with pid [6184]
[iiwa/iiwa_service-2] process has died [pid 6183, exit code 127, cmd /home/zxl5344/IROS2022/devel/lib/iiwa_tools/iiwa_service __name:=iiwa_service __log:=/home/zxl5344/.ros/log/12d921ec-546e-11ec-bb30-45a21bc009e3/iiwa-iiwa_service-2.log].
log file: /home/zxl5344/.ros/log/12d921ec-546e-11ec-bb30-45a21bc009e3/iiwa-iiwa_service-2*.log
process[gazebo_gui-4]: started with pid [6189]
process[urdf_spawner-5]: started with pid [6194]
process[iiwa/iiwa_controller-6]: started with pid [6195]
process[robot_state_publisher-7]: started with pid [6196]
[INFO] [1638559230.273960, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1638559230.279863, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1638559230.282491, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1638559230.674758567]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1638559230.675712349]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1638559230.805449917]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1638559230.806325967]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Service [/physics/info/plugin] is not valid.
Service [/scene_info] is not valid.
Service [/shadow_caster_material_name] is not valid.
Service [/shadow_caster_render_back_faces] is not valid.
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Service [/introspection/tnuhez/filter_new] is not valid.
Service [/introspection/tnuhez/filter_update] is not valid.
Service [/introspection/tnuhez/filter_remove] is not valid.
Service [/introspection/tnuhez/items] is not valid.
Topic [/introspection/tnuhez/items_update] is not valid.
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
[ INFO] [1638559231.572608277]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1638559231.590769368, 0.006000000]: Physics dynamic reconfigure ready.
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
[INFO] [1638559231.786623, 0.196000]: Calling service /gazebo/spawn_urdf_model
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Service [/shadow_caster_material_name] is not valid.
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Service [/shadow_caster_render_back_faces] is not valid.
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Service [/marker/list] is not valid.
Service [/marker] is not valid.
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Invalid partition name [E5-ME-L-KAFI11:zxl5344@AD.PSU.EDU]
Topic [/iiwa/joint_cmd] is not valid.
Service [/iiwa/joint_cmd_req] is not valid.
[INFO] [1638559232.042226, 0.368000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1638559232.113604582, 0.368000000]: Loading gazebo_ros_control plugin
[ INFO] [1638559232.113688934, 0.368000000]: Starting gazebo_ros_control plugin in namespace: /iiwa
[ INFO] [1638559232.114030362, 0.368000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
[ INFO] [1638559232.235252053, 0.368000000]: Loaded gazebo_ros_control.
[INFO] [1638559232.390294, 0.523000]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1638559232.392689, 0.525000]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1638559232.395370, 0.528000]: Loading controller: /iiwa/TorqueController
[INFO] [1638559232.406171, 0.539000]: Loading controller: /iiwa/joint_state_controller
[INFO] [1638559232.414103, 0.547000]: Controller Spawner: Loaded controllers: /iiwa/TorqueController, /iiwa/joint_state_controller
[INFO] [1638559232.418280, 0.551000]: Started controllers: /iiwa/TorqueController, /iiwa/joint_state_controller
[urdf_spawner-5] process has finished cleanly
log file: /home/zxl5344/.ros/log/12d921ec-546e-11ec-bb30-45a21bc009e3/urdf_spawner-5*.log

**Comment by costashatz** [comment]
> /home/zxl5344/IROS2022/devel/lib/iiwa_tools/iiwa_service: error while loading shared libraries: libRBDyn.so.1: cannot open shared object file: No such file or directory

You do not have installed correctly the dependencies for iiwa_service. Please follow the installation instructions..

> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Service [/physics/info/plugin] is not valid.
> Service [/scene_info] is not valid.
> Service [/shadow_caster_material_name] is not valid.
> Service [/shadow_caster_render_back_faces] is not valid.
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Service [/introspection/tnuhez/filter_new] is not valid.
> Service [/introspection/tnuhez/filter_update] is not valid.
> Service [/introspection/tnuhez/filter_remove] is not valid.
> Service [/introspection/tnuhez/items] is not valid.
> Topic [/introspection/tnuhez/items_update] is not valid.
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]
> Invalid partition name [E5-ME-L-KAFI11:[zxl5344@AD.PSU.EDU](mailto:zxl5344@AD.PSU.EDU)]

Overall this seems that you are either mixing ROS versions or your ROS is not installed correctly...
