### ISSUE TITLE
Motion paused during PositionControl

### ISSUE THREAD

**Issue by zxl5344** [epfl-lasa/iiwa_ros#70]
Hi, all

I am using PositionController from repo. I wrote a python code to let robot move from joint angle [0, 0, 0, 0, 0, 0, 0] to joint angle [0.5, 0.2, 0.5, 0.3, 0.5, -0.5, 0.5]. My code works fine on Gazebo. But when I tried to run same code on iiwa, robot paused. The smart pad shows me: 
![image](https://user-images.githubusercontent.com/79371762/133308453-14cc95cc-e73e-4c50-80cd-280142b6c37c.png)
Why does this happen and how do I solve it or avoid it?

Thank you

**Comment by costashatz** [comment]
Hey,

This "smells" like a connection issue. Most probably you do not adhere to (at least) 500Hz. Another possible issue is a bad controller. If you attempt to give very high-velocities/torques, the robot will complain and stop.

**Comment by zxl5344** [comment]
Hi costashatz,

Thanks for your response.
I tried to use Torque Controller and still have the same issues. my frequency is 1000Hz. I set up a limit for max torque at [10, 10, 3., 2., 2., 2., 1.]. I am using a PD controller. My P value are: [800, 800, 800, 800, 300, 50, 10] and D is [1000, 1000, 200, 100, 5, 1, 0.1]. I run my code at stiffness = 500.

Here is my code:

`#!/usr/bin/env python
"""
This node use PD contoller to move robot back to zero position
SUBSCRIBERS:
	- /iiwa/joint_states (JointState)
PUBLISHERS:
	- /iiwa/PositionController/command (Float64MultiArray)
SERVICES:
	- /iiwa/iiwa_ik_server
	- /iiwa/iiwa_fk_server

"""

import rospy
from std_msgs.msg import Float64MultiArray, MultiArrayLayout, MultiArrayDimension
from sensor_msgs.msg import JointState
from iiwa_tools.srv import GetIK, GetIKRequest, GetFK
from geometry_msgs.msg import Pose
import numpy as np


class Move_Torque:
	"""
	this class move robot to a certain joint state with torque input use PD controller
	"""
	
	def __init__(self, _target):
		rospy.loginfo("Robot starts moving")
		self.DT=1/1000							# change frequence to 1000hz
		
		# setup state variables
		self.rob_state=JointState()
		
		# initial storing
		self.measurement = np.zeros(21)
		
		# Torque saturation 
		self.sat = [10, 10, 3., 2., 2., 2., 1.]			# stiffness 500
		
		# initial error of pos
		self.error = [0, 0, 0, 0, 0, 0, 0]
		
		# initial error of velocity
		self.errorV = [0, 0, 0, 0, 0, 0, 0]
		
		# set up P gain
		self.P = [800, 800, 800, 800, 300, 50, 10]
		
		# set up D gain
		self.D = [1000, 1000, 200, 100, 5, 1, 0.1]
		
		# setup publishers, subscribers, timers:
		self.move_pub=rospy.Publisher("/iiwa/TorqueController/command", Float64MultiArray, queue_size=10)
		self.joint_sub=rospy.Subscriber("/iiwa/joint_states", JointState, self.update_state, queue_size=10)
		rospy.wait_for_message("/iiwa/joint_states", JointState)
		self.sim_timer = rospy.Timer(rospy.Duration(self.DT),self.moving)
		
		# setup goal joint state
		self.goal = Float64MultiArray()
		self.goal.data = _target
		
		# setup Torque
		self.Torque = Float64MultiArray()
		self.Torque.data = [0, 0, 0, 0, 0, 0, 0]
		
		# setup IK client
		self.ik_service = '/iiwa/iiwa_ik_server'
		rospy.wait_for_service(self.ik_service)
		self.get_ik = rospy.ServiceProxy(self.ik_service, GetIK)
		self.ikseed=GetIKRequest()	# data type is GetIKRequest
		
		# setup FK client
		self.fk_service = '/iiwa/iiwa_fk_server'
		rospy.wait_for_service(self.fk_service)
		self.get_fk = rospy.ServiceProxy(self.fk_service, GetFK)
		self.seed = Float64MultiArray()
		self.seed.layout = MultiArrayLayout()
		self.seed.layout.dim = [MultiArrayDimension(), MultiArrayDimension()]
		self.seed.layout.dim[0].size = 1
		self.seed.layout.dim[1].size = 7
		self.seed.data = self.rob_state.position
		
		# setup shutdown
		rospy.on_shutdown(self.back2zeros)
		
	def moving(self,data):
		"""
		Publish Torque
		"""
		self.CaluTorque()
		self.move_pub.publish(self.Torque)
		
	def update_state(self,data):
		"""
		update data and storing position, velocity and effort
		"""
		self.rob_state = data
		self.measurement = np.vstack((self.measurement, np.concatenate((self.rob_state.position,self.rob_state.velocity, self.rob_state.effort), axis=None)))
		
	def back2zeros(self):
		"""
		Move robot back to zeros pos and shut down
		"""
		rospy.loginfo("closing node")
		self.goal.data = [0, 0, 0, 0, 0, 0, 0]
		rospy.sleep(15.)
		
		
	def CaluTorque(self):
		"""
		calculate desire Torque
		"""
		
		# calculate error of pos
		self.error[0] = self.goal.data[0] - self.rob_state.position[0]
		self.error[1] = self.goal.data[1] - self.rob_state.position[1]
		self.error[2] = self.goal.data[2] - self.rob_state.position[2]
		self.error[3] = self.goal.data[3] - self.rob_state.position[3]
		self.error[4] = self.goal.data[4] - self.rob_state.position[4]
		self.error[5] = self.goal.data[5] - self.rob_state.position[5]
		self.error[6] = self.goal.data[6] - self.rob_state.position[6]
		
		# calculate error of v
		self.errorV[0] = 0 - self.rob_state.velocity[0]
		self.errorV[1] = 0 - self.rob_state.velocity[1]
		self.errorV[2] = 0 - self.rob_state.velocity[2]
		self.errorV[3] = 0 - self.rob_state.velocity[3]
		self.errorV[4] = 0 - self.rob_state.velocity[4]
		self.errorV[5] = 0 - self.rob_state.velocity[5]
		self.errorV[6] = 0 - self.rob_state.velocity[6]
		
		
		# calculate force
		Force = [0, 0, 0, 0, 0, 0, 0]
		
		Force[0] = np.clip(self.P[0] * self.error[0] + self.D[0] * self.errorV[0], -self.sat[0], self.sat[0])
		Force[1] = np.clip(self.P[1] * self.error[1] + self.D[1] * self.errorV[1], -self.sat[1], self.sat[1])
		Force[2] = np.clip(self.P[2] * self.error[2] + self.D[2] * self.errorV[2], -self.sat[2], self.sat[2])
		Force[3] = np.clip(self.P[3] * self.error[3] + self.D[3] * self.errorV[3], -self.sat[3], self.sat[3])
		Force[4] = np.clip(self.P[4] * self.error[4] + self.D[4] * self.errorV[4], -self.sat[4], self.sat[4])
		Force[5] = np.clip(self.P[5] * self.error[5] + self.D[5] * self.errorV[5], -self.sat[5], self.sat[5])
		Force[6] = np.clip(self.P[6] * self.error[6] + self.D[6] * self.errorV[6], -self.sat[6], self.sat[6])
		
		self.Torque.data = Force
		
	def update_target(self, _newjointstate):
		"""
		update target
		"""
		self.goal.data = _newjointstate
		
	def currentpose(self):
		"""
		print current pose
		"""
		self.seed.data = self.rob_state.position
		self.respFK = self.get_fk(self.seed)
		self.sol_pose = self.respFK.poses[0]
		
		# print out current position
		print('current pose:')
		print(self.sol_pose)
		
	def currentposition(self):
		"""
		print out current position
		"""
		
		print('current joint:')
		`print(self.rob_state.position)`
		

def main():
	"""
	Run the main loop, by instatiating a waver class, and then calling ros.spin
	"""
	rospy.init_node('Torq', log_level=rospy.INFO)
	
	
	try:
		jointstate0 = [0, 0, 0, 0, 0, 0, 0]
		test = Move_Torque(jointstate0)
		
		rospy.loginfo("pose1")
		jointstate1 = [1, 1, 1, 1, 0.5, 0.5, 0.5]
		test.update_target(jointstate1)
		rospy.sleep(10.)
			
		# read current position in world frame
  		test.currentposition()
				
		rospy.loginfo("pose2")
		jointstate2 = [-1, -1, -1, -1, -0.5, -0.5, -0.5]
		test.update_target(jointstate2) 
		rospy.sleep(10.)
			
		# read current position in world frame
		test.currentposition()
		  
	except rospy.ROSInterruptException: 
		pass
	
	rospy.loginfo("task complete")

	rospy.spin()


if __name__=='__main__':
    main()`

**Comment by costashatz** [comment]
> my frequency is 1000Hz

Are you sure that your communication is always at 1000Hz? I am not talking about what you select in iiwa_ros, but the real physical communication.

> I set up a limit for max torque at [10, 10, 3., 2., 2., 2., 1.]. I am using a PD controller. My P value are: [800, 800, 800, 800, 300, 50, 10] and D is [1000, 1000, 200, 100, 5, 1, 0.1]. I run my code at stiffness = 500.

I cannot really tell anything with these values, although the D values look big.

Overall you should be careful with:

- Ensuring the communicate rate at the one you set in KUKA Sunrise Java app
- Sending "smooth" commands (i.e., commands that will not make the robot change in 1-2 timesteps the whole trajectory)

Not sure if I can help more than that without any measurement or analysis from your side.

**Comment by zxl5344** [comment]
Thank you for your help @costashatz 
Could you give me some suggestions about what should I measure to debug this issues. I am a beginner of robotics so your suggestion are very valuable to me.

**Comment by zxl5344** [comment]
I rerun my code this week and my problem magically disappeared. Thank you for your help
