### ISSUE TITLE
Can't connect MoveIt! and gazebo

### ISSUE THREAD

**Issue by mf093087** [epfl-lasa/iiwa_ros#73]
I want to use moveit and gazebo to do co-simulation. I plan the path in RVIZ with moveit, and then if gazebo is connected, the robot in gazebo will also move. 

I use following command to open moveit and gazebo in this repository. 
- roslaunch iiwa_gazebo iiwa_gazebo.launch
- roslaunch iiwa_moveit demo.launch driver:=true

![image](https://user-images.githubusercontent.com/67538561/144758608-208baf4d-9843-4458-9bfd-bf91e4e1909d.png)

The gazebo environment will not move. I think it is not connected properly. I saw this issue 
https://github.com/epfl-lasa/iiwa_ros/issues/33

I tried the following command. 

_In order to make the setup work for you, the only thing you need to change is this line to contain
<arg name="controller" default="PositionTrajectoryController"/>

as an alternative you can also run
roslaunch iiwa_gazebo iiwa_gazebo.launch controller:=PositionTrajectoryController_

But it still doesn't work, can anybody help me?

**Comment by costashatz** [comment]
> * oslaunch iiwa_moveit demo.launch driver:=true

Here you are launching the MoveIt! for the real robot (`driver:=true` does that). You need to run this with `driver:=false`.

**Comment by mf093087** [comment]
> > * oslaunch iiwa_moveit demo.launch driver:=true
> 
> Here you are launching the MoveIt! for the real robot (`driver:=true` does that). You need to run this with `driver:=false`.

Thanks a lot, I solved this problem. I need to change the controller from Torque controller to positiontrajectory controller.
