### ISSUE TITLE
ROS has been disconnected

### ISSUE THREAD

**Issue by zxl5344** [epfl-lasa/iiwa_ros#74]
Hi, 

I am using a torque controller for my control research. iiwa always disconnects with PC without any warning or error. The smartPad only show  'ROS has been disconnected'. 
![ROSDISCONNECT](https://user-images.githubusercontent.com/79371762/145114339-bc4ded2b-4f49-40e5-9fe8-66072f068e2a.jpeg)
However, when I switch to another application on smartPad and run it, I get this error

![ROSDISCONNECT1](https://user-images.githubusercontent.com/79371762/145114485-564fef28-d88f-4b86-a984-5b5f94e71280.jpeg)

Does anyone have clue about the cause of my problem? Thank you!

**Comment by costashatz** [comment]
> 'ROS has been disconnected'.

This most probably means that you haven't configured the network setup correctly. Please check the README on how to do it properly.

**Comment by LJXASD** [comment]
Hello, I have also encountered this problem, "ros has been disconnected".
Have you solved this problem?
Thanks a lot! 

> Hi,
> 
> I am using a torque controller for my control research. iiwa always disconnects with PC without any warning or error. The smartPad only show 'ROS has been disconnected'. ![ROSDISCONNECT](https://user-images.githubusercontent.com/79371762/145114339-bc4ded2b-4f49-40e5-9fe8-66072f068e2a.jpeg) However, when I switch to another application on smartPad and run it, I get this error
> 
> ![ROSDISCONNECT1](https://user-images.githubusercontent.com/79371762/145114485-564fef28-d88f-4b86-a984-5b5f94e71280.jpeg)
> 
> Does anyone have clue about the cause of my problem? Thank you!
