### ISSUE TITLE
Can we use moveit setup assistant to edit the file? unable to locate the URDF file in package. Expected File: /home/user/catkin_iiwa/src/iiwa_ros/iiwa_description/urdf/iiwa14.urdf

### ISSUE THREAD

**Issue by mf093087** [epfl-lasa/iiwa_ros#79]
I want to use moveit setup assistant to edit the configuration file. However, it doesn't work for me. Can anybody help me?

unable to locate the URDF file in package. Expected File: /home/user/catkin_iiwa/src/iiwa_ros/iiwa_description/urdf/iiwa14.urdf

![image](https://user-images.githubusercontent.com/67538561/152329961-46978b20-8b9d-428a-9327-32a8f0fbf14a.png)

**Comment by costashatz** [comment]
Hello. Thanks for using the library.

I think you need to generate the file (iiwa14.urdf) using the [xacro file](https://github.com/epfl-lasa/iiwa_ros/blob/master/iiwa_description/urdf/iiwa14.urdf.xacro) provided in the `iiwa_description` package. @ymollard did the MoveIt! integration though, so he might know better.

**Comment by mf093087** [comment]
thanks a lot!
