### ISSUE TITLE
Direct Servo / Connectivity Package needed?

### ISSUE THREAD

**Issue by MonsisGit** [epfl-lasa/iiwa_ros#80]
Hi everybody,

I was wondering if I can run this package without the direct servo and connectivity packages. ( They are needed for [IFL-CAMP/iiwa_stack](https://github.com/IFL-CAMP/iiwa_stack) ) I have Sunrise 1.16 and these packages are not available. However I have the FRI package.

Thanks for the help :)

**Comment by costashatz** [comment]
I have no clue! @matthias-mayr @ymollard @JimmyDaSilva any ideas?

**Comment by JimmyDaSilva** [comment]
Hi @MonsisGit,
Yes, I use FRI only, and I only have following extensions ON:

- Fast Robot Interface Extension
- Enhanced Velocity Controller
- Human Robot Collaboration
- ...

**Comment by costashatz** [comment]
Great!
