### ISSUE TITLE
fatal error: pluginlib/class_list_macros.hpp: No such file or directory

### ISSUE THREAD

**Issue by victoralad** [epfl-lasa/iiwa_ros#83]
It appears that the customEffortController was not added as an executable in the CMakelist.txt file. When I added it and tried to compile using `catkin build iiwa_ros`, I get the error `fatal error: pluginlib/class_list_macros.hpp: No such file or directory`. Is this something that anyone else has run into?
In short, how do you run the `CustomEffortController`? When I tried `rosrun iiwa_control CustomEffortController`, I get the error stating that no such executable was found.

**Comment by victoralad** [comment]
I figured out that the customEffortController does not need to be added as an executable. To use the controller, I just needed to add it to my iiwa_control.lauch file

**Comment by costashatz** [comment]
Ah yes! You do not need to add it as an executable. It is a plugin to be loaded. Sorry for not answering your issue. I was on vacations.
